### ISSUE TITLE
Next CSS Transformations

### ISSUE THREAD

**Issue by Braden1996** [kwonoj/swc-plugin-vanilla-extract#5]
Hey - thanks for the great plugin!

Seems to work _almost_ perfectly out the box for Next 13 on my project.
The only issue I've found is that vendor prefixes aren't applied to the compiled CSS. Next applies a bunch of [handy PostCSS transformations](https://nextjs.org/docs/advanced-features/customizing-postcss-config). Is there anyway we can pipe the output of this plugin through those? I'm not that familiar with Rust, SWC, or Next's internals so don't even know where to begin!

**Comment by kwonoj** [comment]
Unfortunately I do not believe this is trivially possible as far as I know at this moment, though I may wrong.

Original upstream vanilla-extract author said they'll moving away from babel plugin (https://github.com/vanilla-extract-css/vanilla-extract/discussions/478#discussioncomment-3641334) anyway, which I expect naturally deprecate this plugin anytime soon.

**Comment by kwonoj** [comment]
Closing as same https://github.com/kwonoj/swc-plugin-vanilla-extract/issues/9#issuecomment-1535773963
