### ISSUE TITLE
NextJS 13 Setup

### ISSUE THREAD

**Issue by jherr** [kwonoj/swc-plugin-vanilla-extract#6]
Would it be possible to add a section to the README on configuring this plugin for NextJS 13?

**Comment by kwonoj** [comment]
Curious what exact piece is missing?

**Comment by jherr** [comment]
Thanks for getting back so quickly. Coupla things:

1. A simple blurb on whether or not it's possible using this to enable using @vanilla-extract/css with RSCs?
2. A step by step process showing how to configure or create the relevant files (`next.config.js` and `.swcrc`) assuming a clean NextJS 13 project with the experiment app directory configured and @vanilla-extract/css and swc-plugin-vanilla-extract installed.

I'd totally write it myself and PR it, I just don't know how to do it. I can't even read the source since it's just a `wasm` file.

**Comment by kwonoj** [comment]
Sorry, I don't believe that belong to this repo. next.js should have a document already for the configuring plugins already and that should be a proper guidance to enabling plugins. 

I'm not sure about RSC as I haven't tried myself, but unless there's a bug do not see major reason not to work if vanilla-extract itself is not supported.
