### ISSUE TITLE
Segmentation fault in docker build

### ISSUE THREAD

**Issue by samithaf** [kwonoj/swc-plugin-vanilla-extract#9]
Thank you for the plugin and everything works fine in my Mac machine. However it fails with error message "Segmentation fault (core dumped)". If I remove swc-plugin-vanilla-extract plugin then it's working fine. I am new to Rust and would be great if you could help. Thanks!

swc file

```
{
	"jsc": {
		"experimental": {
			"plugins": [
				["swc-plugin-vanilla-extract", {}]
			]
		},
		"parser": {
			"syntax": "typescript"
		},
		"target": "es2017",
		"loose": false,
		"minify": {
			"compress": false,
			"mangle": false
		}
	},
	"minify": false,
	"isModule": true,
	"exclude": [".*\\.spec|test\\.(j|t)s$"]
}
```

Docker image type:
 x86_64 x86_64 x86_64 GNU/Linux

SWC version
    "@swc/cli": "^0.1.62",
    "@swc/core": "1.3.30",

**Comment by kwonoj** [comment]
Since original upstream vanilla-extract moves away from plugin (https://github.com/vanilla-extract-css/vanilla-extract/discussions/478#discussioncomment-3641334) this plugin is not actively maintained at this moment. 

I'm happy to accept PR for the fixes, but unfortunately I do not have enough time to investigate issue.

**Comment by samithaf** [comment]
Hi @kwonoj, Looks like setFileScope trying to get the path from root and @vanilla-extract/vite-plugin for an e.g. only get the path from project root. Is there a way to file scope path? I can see an option to override the package name. Sorry I know Vanilla Extract team is not using it but it's required during unit testing. Any assistance highly appreciative.
